import { Eye, EyeOff } from "lucide-react";
import { useState } from "react";
import { FormField, IconButton, Input, Select } from "@/components/ui";
import { MODEL_PROVIDERS, getProviderPreset, type AppConfig, type ModelProvider } from "@/types";

export function OfficialApiPanel({ config, setConfig, onProviderChange, onApiKeyChange }: { config: AppConfig; setConfig: (patch: Partial<AppConfig>) => void; onProviderChange: (provider: ModelProvider) => void; onApiKeyChange: (value: string) => void }) {
  const [showKey, setShowKey] = useState(false); const custom=config.provider==="custom"; const preset=getProviderPreset(config.provider);
  return <div className="space-y-4"><FormField label="模型供应商" hint="选择内置供应商后无需填写 Base URL 与模型名称"><Select value={config.provider} onChange={(event)=>onProviderChange(event.target.value as ModelProvider)}>{MODEL_PROVIDERS.map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</Select></FormField><FormField label="模型名称" hint={custom?"兼容 OpenAI Chat Completions 的模型 ID":"从该供应商的内置模型中选择"}>{custom?<Input value={config.model} onChange={(event)=>setConfig({model:event.target.value})} placeholder="gpt-4o-mini"/>:<Select value={config.model} onChange={(event)=>setConfig({model:event.target.value})}>{preset?.models.map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</Select>}</FormField><FormField label="API Key" hint="不会在日志或界面中明文展示"><div className="relative"><Input type={showKey?"text":"password"} value={config.apiKey} onChange={(event)=>onApiKeyChange(event.target.value)} placeholder="sk-..." className="pr-10"/><IconButton label={showKey?"隐藏 API Key":"显示 API Key"} size="sm" onClick={()=>setShowKey(!showKey)} className="absolute right-1 top-1/2 -translate-y-1/2">{showKey?<EyeOff/>:<Eye/>}</IconButton></div></FormField>{custom?<FormField label="API Base URL" hint="兼容 OpenAI Chat Completions 的接口地址"><Input value={config.baseUrl} onChange={(event)=>setConfig({baseUrl:event.target.value})} placeholder="https://api.openai.com/v1"/></FormField>:null}</div>;
}
